apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: product-api-sm
  namespace: monitoring
  labels:
    release: prometheus
spec:
  namespaceSelector:
    matchNames:
      - techcommerce
  selector:
    matchLabels:
      app: product-api
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: order-api-sm
  namespace: monitoring
  labels:
    release: prometheus
spec:
  namespaceSelector:
    matchNames:
      - techcommerce
  selector:
    matchLabels:
      app: order-api
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
