apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-api
  namespace: staging
  labels:
    app: order-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: order-api
  template:
    metadata:
      labels:
        app: order-api
    spec:
      containers:
      - name: order-api
        image: order-api:dev
        ports:
        - containerPort: 4000
        readinessProbe:
          httpGet:
            path: /readyz
            port: 4000
          initialDelaySeconds: 5
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /healthz
            port: 4000
          initialDelaySeconds: 15
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: order-api
  namespace: staging
spec:
  selector:
    app: order-api
  ports:
  - name: http
    port: 4000
    targetPort: 4000
  type: ClusterIP
