apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-api
  namespace: staging
  labels:
    app: product-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: product-api
  template:
    metadata:
      labels:
        app: product-api
    spec:
      containers:
      - name: product-api
        image: product-api:dev
        ports:
        - containerPort: 5000
        env:
        - name: LOG_LEVEL
          value: "info"
        readinessProbe:
          httpGet:
            path: /readyz
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 2
        livenessProbe:
          httpGet:
            path: /healthz
            port: 5000
          initialDelaySeconds: 15
          periodSeconds: 10
        resources:
          requests:
            cpu: "200m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: product-api
  namespace: staging
  labels:
    app: product-api
spec:
  selector:
    app: product-api
  ports:
  - name: http
    port: 5000
    targetPort: 5000
  type: ClusterIP
