apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: app-alerts
  namespace: monitoring
spec:
  groups:
  - name: app.rules
    rules:
    - alert: HighPodRestarts
      expr: sum(rate(kube_pod_container_status_restarts_total[10m])) by (pod) > 3
      for: 1m
      labels:
        severity: warning
      annotations:
        summary: "Pod restarting frequently ({{ $labels.pod }})"
        description: "Pod restarts exceeded 3 in 10m."
    - alert: HighLatency
      expr: histogram_quantile(0.95, sum(rate(http_server_request_duration_seconds_bucket[5m])) by (le,service,endpoint)) > 2
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: "High 95th percentile latency > 2s"
        description: "Service {{ $labels.service }} p95 latency exceeded 2s."
    - alert: HighErrorRate
      expr: (sum(rate(http_requests_total{status=~'5..'}[5m])) by (service)) / (sum(rate(http_requests_total[5m])) by (service)) > 0.05
      for: 5m
      labels:
        severity: critical
      annotations:
        summary: "High error rate > 5%"
        description: "Service {{ $labels.service }} 5xx error ratio > 5%."
    - alert: HighDiskUsage
      expr: (node_filesystem_size_bytes{fstype!~'tmpfs|overlay'} - node_filesystem_free_bytes{fstype!~'tmpfs|overlay'}) / node_filesystem_size_bytes{fstype!~'tmpfs|overlay'} > 0.85
      for: 10m
      labels:
        severity: warning
      annotations:
        summary: "Disk usage > 85%"
        description: "Instance {{ $labels.instance }} has high disk usage."
